### ISSUE TITLE
Issue when running pre-trained model

### ISSUE THREAD

**Issue by debayan** [technicolor-research/dsve-loc#1]
$ CUDA_VISIBLE_DEVICES=1 python3 semantic_seg.py -p models/best_model.pth.tar
Loading model from: models/best_model.pth.tar
loading annotations into memory...
Done (t=4.44s)
creating index...
index created!
Traceback (most recent call last):
  File "semantic_seg.py", line 71, in <module>
    dataset = CocoSemantic(transform=prepro_val)
  File "/media/data/dbanerjee/dsve-loc/misc/dataset.py", line 162, in __init__
    params = np.load(path_params, encoding='latin1')
  File "/media/data/dbanerjee/dsve-loc/lib/python3.5/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/utable.npy'

**Comment by M-Eng** [comment]
Hi,
You need to download the word embedding files, and update their path in the file misc/config.py.
All the download links are available in the data/readme and in the config file.

**Comment by debayan** [comment]
Sorry, my bad
