### ISSUE TITLE
about GPU memory

### ISSUE THREAD

**Issue by zl535320706** [technicolor-research/dsve-loc#4]
I want to know, how many GPUs do you used in your experiment, thanks.

**Comment by M-Eng** [comment]
For training the main model, I used 4 GPUs in parallel.

**Comment by zl535320706** [comment]
> For training the main model, I used 4 GPUs in parallel.

4 1080ti？ or titan xp？

**Comment by M-Eng** [comment]
4 P100, you can probably do with less by putting the image pipeline on separates GPUs from the text pipeline. The SRU cannot be parallelized but it should fit on a single GPU.
