### ISSUE TITLE
File visual_genome.py missing

### ISSUE THREAD

**Issue by BelaChakraborty** [technicolor-research/dsve-loc#6]
Hello,

I was trying to run your code and while running, /dsve-loc/blob/master/misc/dataset.py, in line 36, we have:
 from visual_genome import local as vg

I tried searching this but it's nowhere present, I was just wondering that is this file missing from the repo and what's the exact need for it?

Would be grateful if you could kindly guide..

Thank you

Regards
Bela

**Comment by M-Eng** [comment]
Hi,

you need to install the corresponding python package, it's available on pip (https://pypi.org/project/visual-genome/)
You only need this package to run the localization evaluation (pointing game), if you don't need these evaluations you can comment the import line.

all the packages used to run this code and their version are available in the environment.yml file
