### ISSUE TITLE
New-style autograd function with static forward method

### ISSUE THREAD

**Issue by BelaChakraborty** [technicolor-research/dsve-loc#7]
Hello,

There is another issue encountered when I am executing train.py:

/opt/conda/conda-bld/pytorch_1573049306803/work/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method

Is there a fix for this issue? 
![Screenshot from 2019-11-29 16-30-51](https://user-images.githubusercontent.com/51686727/69845901-5f4e1a00-12c6-11ea-8d19-93605df969e7.png)

**Comment by M-Eng** [comment]
Hi,
The code was tested with pytorch=1.0, you can downgrade your pytorch version to remove this warning. 
Also it's only a warning, so the code might still work under pytorch=1.3 but we haven't tested it.

**Comment by BelaChakraborty** [comment]
Hello..

Thank you so much for taking out time and responding to my queries..

I am really grateful

Regards
Bela

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
