### ISSUE TITLE
Difference in pointing game results

### ISSUE THREAD

**Issue by BelaChakraborty** [technicolor-research/dsve-loc#8]
Hello,

I would be grateful if you could kindly guide me a bit in the following issue:

I trained the framework and the retrieval results are almost matching quite well. Below is the screenshot:
![Screenshot from 2019-12-09 14-39-09](https://user-images.githubusercontent.com/51686727/70415057-e4e47d80-1aaf-11ea-8209-8746f0f3c99a.png)

But when I test the pointing game, I don't know where I am going wrong. Following are the results( only around 11.24%):
![Screenshot from 2019-12-09 18-09-33](https://user-images.githubusercontent.com/51686727/70415125-0ba2b400-1ab0-11ea-94d0-c25e03e2e6a0.png)

Below is the best_model.pth.tar which I get from my training:
![Screenshot from 2019-12-09 18-17-05](https://user-images.githubusercontent.com/51686727/70415165-22e1a180-1ab0-11ea-8b93-e06eaf10b9e0.png)

As you can see from the above screenshot, I tested with your model as well: author_best_model.pth.tar, which gives me the following results:
![Screenshot from 2019-12-09 19-06-01](https://user-images.githubusercontent.com/51686727/70418212-1c0a5d00-1ab7-11ea-863e-8ceb7956ac63.png)

Below are the paths specified to the config.py file:
![Screenshot from 2019-12-09 18-18-51](https://user-images.githubusercontent.com/51686727/70415271-60dec580-1ab0-11ea-8881-1976371e4bbc.png)

I would be really grateful if you could help me out with this as maybe I am getting confused or making some mistake.

Thank you

Regards
Bela

**Comment by M-Eng** [comment]
Hello,

have you made any modification to the code? Maybe to make it run in a more recent environment?

If you haven't, there still seems to have an error in the data you are using.
From your log of the pointing, it seems that you are missing some data. If I remember correctly, you should have a bit more than 17k images and you only have 16k.

Since you managed to replicate the retrieval results, I would assume your files for the Ms-CoCo dataset are correct, the problem might be on the visual-genome side.

here is what I have in my "VG_ANN" folder 

![image](https://user-images.githubusercontent.com/8820331/70429434-cb740f00-1a78-11ea-8773-40ca80ba263c.png)

And in the "VG_IMAGE" folder I have 108249 images

Check if you have the same things in both folder.

Best,
Martin

**Comment by BelaChakraborty** [comment]
Hello,

First of all, I am very grateful for your prompt response and your time. 

Maybe I am going wrong somewhere fundamental, so let me just begin with the VG data which I have. I have actually taken Visual_Genome Version 1.0, 2015 for the VG_IMAGE and VG_ANN in the config file( is the correct one?) :
<img width="1070" alt="Screenshot 2019-12-09 at 10 44 36 PM" src="https://user-images.githubusercontent.com/51686727/70434025-42d88b80-1ad7-11ea-8a35-e1e76b1e66b9.png">

Next, I did some change as very strangely I got some error when the code was executing through line 73 of pointing_game.py: 
<img width="560" alt="Screenshot 2019-12-09 at 10 40 12 PM" src="https://user-images.githubusercontent.com/51686727/70434108-6d2a4900-1ad7-11ea-80c6-5e341bac247f.png">

This kind of migrated to local.py in line 36 under the "def get_all_region_descriptions" and gave error in appending the image["regions"] as it told keyerror[0], when I printed them, it had empty value. So I put it under a try-except. So was wondering if I downloaded wrong files. You can see the change below:
<img width="460" alt="Screenshot 2019-12-09 at 10 41 44 PM" src="https://user-images.githubusercontent.com/51686727/70434299-f2adf900-1ad7-11ea-847b-71ce05359f3e.png">

I was also wondering as wrt to the files given from the dataset, I couldn't understand what mistake was it..

Regards
Bela

**Comment by M-Eng** [comment]
I think the problem is coming from the visual genome files you are using. I used the Version 1.2.
If you revert your code modification and use the 1.2 files it should solve your issues.

Best,
Martin

**Comment by BelaChakraborty** [comment]
Hello

Thank you for ur suggestion. I had tried version 1.2 as well.. but maybe I might have gone wrong.

I would re-try and get back to u on it with specific error if I come across

Thanks

Regards
Bela

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BelaChakraborty** [comment]
Hello,

As per your instruction, I did change the visual_genome files and it did have 17k odd images. Thank you very much for your suggestion

I just had one more question regarding the phrase localization script, pointing_game.py. 
From the screenshot below, in line 124, it calls compute_pointing_game_acc.
![Screenshot from 2019-12-10 16-11-31](https://user-images.githubusercontent.com/51686727/70498113-7ebc3100-1b69-11ea-906d-5cbd04c7fe3d.png)

It goes to the localization.py, line 117. I was
![Screenshot from 2019-12-10 16-11-39](https://user-images.githubusercontent.com/51686727/70498200-bd51eb80-1b69-11ea-828c-4d5911879c2a.png)
 just wondering the reason to the "for-loop" from line 121. 

Can't the localization by done directly as dot product of "prod = np.dot(fc_w, act_map)", line 74?
Why the computation of another heat_map in line 84. 
![Screenshot from 2019-12-10 16-11-53](https://user-images.githubusercontent.com/51686727/70498326-1e79bf00-1b6a-11ea-8f12-4ccb299246bd.png)

Would be grateful if you could tell me, it would help me immensely.

Thank you
Regards
Bela

**Comment by M-Eng** [comment]
Hello,

It might be possible to compute the heat maps differently, but both operation line 74 and 84 are necessary.
For clarification you can look at equation 8 and 9 in the [paper](http://openaccess.thecvf.com/content_cvpr_2018/CameraReady/3272.pdf).
Line 74 is equation 8 and line 84 is equation 9.

Put simply, line 74 does a projection of the spatial information coming from the Resnet to the joint embedding space. At this point no caption have been used.
Next, the for loop generates the heat maps for each caption associated to that image. it is in line 84 that the textual grounding happen.

Best,
Martin
