### ISSUE TITLE
Resuming training from a particular EPOCH

### ISSUE THREAD

**Issue by BelaChakraborty** [technicolor-research/dsve-loc#9]
Hello,

I was trying to make the training resume from a particular epoch, was just wondering a few things as I am facing too many issues when I just want to resume from a particular epoch.

To resume from a particular epoch, I had added the following lines of code:
![Screenshot from 2019-12-17 19-21-49](https://user-images.githubusercontent.com/51686727/70977681-85671d00-2102-11ea-8de0-25febe71a12a.png)

Which gave me the following error:
![Screenshot from 2019-12-17 19-23-42](https://user-images.githubusercontent.com/51686727/70977822-c8c18b80-2102-11ea-83ec-5aab4aa2f750.png)

So was checking a few things into the optimizer, printed out a few things as I got the errors:
![Screenshot from 2019-12-17 19-25-26](https://user-images.githubusercontent.com/51686727/70977951-032b2880-2103-11ea-9220-eeda4ecc181f.png)

Below is the corresponding output:
![Screenshot from 2019-12-17 19-26-24](https://user-images.githubusercontent.com/51686727/70978064-32419a00-2103-11ea-93ae-b04a79e6bc19.png)

The error is the same. Was wondering if it can be resumed from a particular epoch because you have added another param_groups in lines 300 and line 316 below:
![Screenshot from 2019-12-17 19-27-49](https://user-images.githubusercontent.com/51686727/70978172-61580b80-2103-11ea-8e15-96fa96cbb202.png)

I tried finding the solution to this issue, somehow it's not loading the optimizer and keeps giving the error: ValueError: loaded state dict has a different number of parameter groups.

How can this issue be resolved in that code, I tried to add the initial_lr but doesn't help. Would you please guide in this issue? As if sometimes the program exits in 56th Epoch, due to the out-of-memory issue, I have to like re-start from the first epoch. I was just wondering why is it giving this issue.

Thank you

Regards
Bela

**Comment by M-Eng** [comment]
Adding the initial lr is not enough, I think you need to add the param groups to the optimizer before loading the optimizer state dict. And it needs to depends on the epoch checkpoint. after epoch one you only add one group after args.fepoch you add both.

It is not tested but the code should look something like that.

```python
#When loading checkpoint

if checkpoint["epoch"] > 1:
    optimizer.add_param_group({'params': join_emb.cap_emb.parameters(), 'lr': optimizer.param_groups[0]
                                       ['lr'], 'initial_lr': args.lr})
    lr_scheduler = MultiStepLR(optimizer, args.lrd[1:], gamma=args.lrd[0])
if checkpoint["epoch"] > checkpoint["args_dict"].fepoch:
    optimizer.add_param_group({'params': filter(lambda p: p.requires_grad, join_emb.img_emb.module.base_layer.parameters()), 'lr': optimizer.param_groups[0]
                                       ['lr'], 'initial_lr': args.lr})
    lr_scheduler = MultiStepLR(optimizer, args.lrd[1:], gamma=args.lrd[0])

lr_scheduler.step(checkpoint["epoch"])
```

Best,
Martin

**Comment by BelaChakraborty** [comment]
Hello

Thank you for your suggestion. It did work.

This resume issue makes me wonder about a few things. I am a bit unclear when it comes to the explanation in the paper under the subsection FULL MODEL TRAINING under 4.1 Experiments. Does it mean that you are training the image and the text pipeline with a different set of parameters for 8 epochs and then different parameters for the rest? Does after 8th epoch till the 59th epoch - it's fine-tuning?

In this code, which you can see below, I am a bit hazy from lines 329 to 352. You optimize text pipeline after one epoch with different optimizer param_groups, then fine-tuning starts after the 8th epoch with again different optimization parameters along with freezing the first layer of RESNET. Why different sets of "optimizers param_groups" under a particular epoch range? Was there any specific need behind it?
![Screenshot from 2019-12-18 13-18-38](https://user-images.githubusercontent.com/51686727/71060825-ac812580-21ba-11ea-854d-90f76a50a108.png)

Because it did affect the resume training, it would actually help me better understand it.

Thank you

Regards
Bela
